bind 0.0.0.0
port 6379
protected-mode no
daemonize no
supervised systemd
pidfile /run/redis/redis-server.pid

loglevel notice
logfile ""
databases 16

save ""
appendonly no
dir /var/lib/redis
dbfilename dump.rdb

repl-diskless-sync yes
repl-diskless-sync-delay 0

include /etc/redis/role.conf
