bind 0.0.0.0
protected-mode no
port 6379
daemonize no
supervised no
save ""
appendonly no
dir /tmp
dbfilename redis-bench-unused.rdb
maxmemory 256mb
maxmemory-policy noeviction
io-threads 1
hz 10
dynamic-hz no
loglevel warning
logfile /tmp/redis-bench.log
pidfile /tmp/redis-bench.pid
